services:
  turtlebot4-workspace:
    image: ghcr.io/collaborativeroboticslab/turtlebot4-workspace:jazzy
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID=${ROBOT_ROS_DOMAIN_ID:-10}
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DISCOVERY_SERVER=${ROBOT_ROS_DISCOVERY_SERVER:-10.0.0.192:11811}
      - NO_AT_BRIDGE=1
      - QT_X11_NO_MITSHM=1
    restart: unless-stopped
    network_mode: host
    ipc: host
    tty: true
    stdin_open: true
    volumes:
      - /dev:/dev:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./turtlebot4-workspace/workspace:/workspace:rw
      - ./turtlebot4-workspace/code-server/config:/root/.config/code-server:rw
      - ./turtlebot4-workspace/code-server/data:/root/.local/share/code-server:rw